export const flowChartData = {
  edgeList: [
    {
      controlUid: 1,
      controlId: "CTRL-A00002",
      controlName: "소명요청",
      controlType: "COMMON",
      startTaskUid: 1,
      endTaskUid: 2,
      startTaskId: "TASK-A000010",
      endTaskId: "TASK-A000011",
      style: "right_start",
      edgePointInfo: null,
      isDelete: null,
    },
  ],
  nodeList: [
    {
      taskUid: 1,
      taskId: "TASK-A000010",
      taskType: "DETEC",
      taskTypeName: "탐지",
      taskName: "탐지",
      taskActor: "SCENARIO_MAIN_OWNER",
      taskActorTypeName: "시나리오 대표 오너",
      dipTop: 150,
      dipLeft: 180,
      width: 90,
      height: 50,
      detailView: "DetectResponseDetect",
      isForceTerminationPossible: null,
      isFileUse: "N",
      isUseAutoNextTask: "N",
      autoNextTaskUid: null,
    },
    {
      taskUid: 2,
      taskId: "TASK-A000011",
      taskType: "EXPRE_REQ",
      taskTypeName: "소명 요청",
      taskName: "소명요청",
      taskActor: "DETECT_EXP_ACTOR",
      taskActorTypeName: "소명 대응자",
      dipTop: 350,
      dipLeft: 180,
      width: 100,
      height: 50,
      detailView: "DetectResponseCallingRequest",
      isForceTerminationPossible: null,
      isFileUse: "Y",
      isUseAutoNextTask: "N",
      autoNextTaskUid: null,
    },
  ],
};
